[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:nginx]
process_name=%(program_name)s_%(process_num)02d
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
numprocs=1
user=root
startsecs=10
stopasgroup=true
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log

[program:php-fpm]
process_name=%(program_name)s_%(program_num)02d
command=/usr/local/sbin/php-fpm --nodaemonize
autostart=true
autorestart=true
numprocs=1
user=www-data
stderr_logfile=/var/log/php-fpm.err.log
stdout_logfile=/var/log/php-fpm.out.log
stopasgroup=true

[program:websocket]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/html/public/ws-server
command=node server.js
autostart=true
autorestart=true
numprocs=1
user=www-data
environment=PORT=%(ENV_WS_PORT)s,WS_PORT=%(ENV_WS_PORT)s,NODE_ENV=production
stderr_logfile=/var/log/websocket.err.log
stdout_logfile=/var/log/websocket.out.log
stopasgroup=true

[group:webservices]
programs=nginx,laravel-serve,websocket
priority=999
